/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFrame;

import java.math.BigInteger;
import javax.swing.ImageIcon;
import static pClases.CFormatoTiempo.mTiempoFinalPP;
import static pGenerarConjunto.CCalcularConvinaciones.mCalcularSubconjuntos;
import pGenerarConjunto.CGenerar;
import pProcesoParalelo.CProcesosParalelo;

///////////////////////////////////////////////////////////////////////////
import static pClases.CFormatoTiempo.*;
import static pFrame.FParalelo.*;

/**
 *
 * @author leand
 */
public class FParalelo extends javax.swing.JFrame
{

    /**
     * Creates new form Frame
     */
    public FParalelo()
    {
        initComponents();
        vBotonDetener.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        vBotonGenerador = new javax.swing.JButton();
        vLabelTotalPP = new javax.swing.JLabel();
        vLabelTiempoEjecPP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        vTextFileNumMax = new javax.swing.JTextField();
        vBotonDetener = new javax.swing.JButton();
        vScrollConjunto = new javax.swing.JScrollPane();
        vTextAreaConjunto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        vTextFileNumExacto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        vBotonRegresar = new javax.swing.JButton();
        vLabelNumConjuntoInfo = new javax.swing.JLabel();
        vLabelNumConjunto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        vTextAreaTodoSubconjuntoPP = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        vTextAreaSubconjuntos0PP = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(750, 600));

        jPanel2.setBackground(new java.awt.Color(65, 77, 15));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setBackground(new java.awt.Color(221, 167, 123));

        vBotonGenerador.setBackground(new java.awt.Color(0, 0, 0));
        vBotonGenerador.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        vBotonGenerador.setForeground(new java.awt.Color(240, 240, 240));
        vBotonGenerador.setText("Generar conjunto y resultados");
        vBotonGenerador.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vBotonGeneradorActionPerformed(evt);
            }
        });

        vLabelTotalPP.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        vLabelTotalPP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLabelTotalPP.setText("Total de subconjuntos: ");

        vLabelTiempoEjecPP.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        vLabelTiempoEjecPP.setText("Tiempo de ejecución:");

        jLabel1.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel1.setText("Longitud de forma random para generar: 3 al");

        vTextFileNumMax.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        vTextFileNumMax.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        vTextFileNumMax.setText("10");
        vTextFileNumMax.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                vTextFileNumMaxFocusGained(evt);
            }
        });
        vTextFileNumMax.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                vTextFileNumMaxKeyTyped(evt);
            }
        });

        vBotonDetener.setBackground(new java.awt.Color(0, 0, 0));
        vBotonDetener.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        vBotonDetener.setForeground(new java.awt.Color(245, 245, 245));
        vBotonDetener.setText("Detener");
        vBotonDetener.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vBotonDetenerActionPerformed(evt);
            }
        });

        vScrollConjunto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Conjunto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        vScrollConjunto.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        vTextAreaConjunto.setEditable(false);
        vTextAreaConjunto.setColumns(20);
        vTextAreaConjunto.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        vTextAreaConjunto.setRows(5);
        vTextAreaConjunto.setToolTipText("");
        vTextAreaConjunto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        vScrollConjunto.setViewportView(vTextAreaConjunto);

        jLabel2.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel2.setText("Longitud exacta del conjunto:");

        vTextFileNumExacto.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        vTextFileNumExacto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        vTextFileNumExacto.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                vTextFileNumExactoFocusGained(evt);
            }
        });
        vTextFileNumExacto.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                vTextFileNumExactoKeyTyped(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);

        vBotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pImagenes/iRegresar32.png"))); // NOI18N
        vBotonRegresar.setBorderPainted(false);
        vBotonRegresar.setContentAreaFilled(false);
        vBotonRegresar.setPreferredSize(new java.awt.Dimension(40, 40));
        vBotonRegresar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBotonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBotonRegresarMouseExited(evt);
            }
        });
        vBotonRegresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vBotonRegresarActionPerformed(evt);
            }
        });

        vLabelNumConjuntoInfo.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        vLabelNumConjuntoInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLabelNumConjuntoInfo.setText("Longitud del conjunto: ");

        vLabelNumConjunto.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        vLabelNumConjunto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLabelNumConjunto.setText("-");

        jLabel3.setFont(new java.awt.Font("Javanese Text", 1, 25)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Calculo de subconjuntos en Paralelo");

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Todos los subconjuntos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        vTextAreaTodoSubconjuntoPP.setEditable(false);
        vTextAreaTodoSubconjuntoPP.setColumns(20);
        vTextAreaTodoSubconjuntoPP.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        vTextAreaTodoSubconjuntoPP.setRows(5);
        jScrollPane3.setViewportView(vTextAreaTodoSubconjuntoPP);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subconjuntos que suman 0", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP));

        vTextAreaSubconjuntos0PP.setEditable(false);
        vTextAreaSubconjuntos0PP.setColumns(20);
        vTextAreaSubconjuntos0PP.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        vTextAreaSubconjuntos0PP.setRows(5);
        jScrollPane4.setViewportView(vTextAreaSubconjuntos0PP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vTextFileNumMax, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vTextFileNumExacto, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vLabelTiempoEjecPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vBotonDetener)
                        .addContainerGap())
                    .addComponent(vLabelTotalPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(vScrollConjunto)
                        .addGap(12, 12, 12))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(vBotonGenerador, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addGap(234, 234, 234))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vBotonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vLabelNumConjunto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vLabelNumConjuntoInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vBotonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vTextFileNumExacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vTextFileNumMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(vBotonGenerador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vScrollConjunto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vLabelNumConjuntoInfo)
                .addGap(0, 0, 0)
                .addComponent(vLabelNumConjunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vLabelTotalPP)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vLabelTiempoEjecPP)
                    .addComponent(vBotonDetener))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vBotonGeneradorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vBotonGeneradorActionPerformed
    {//GEN-HEADEREND:event_vBotonGeneradorActionPerformed
        vBotonDetener.setEnabled(true);
        vBotonGenerador.setEnabled(false);
        vPausar = false;
        setCursor(WAIT_CURSOR);
        if (vNumRandomP)
        {
            if (vTextFileNumMax.getText().length() == 0)
            {
                vTextFileNumMax.setText("10");
            } else
            {
                if (Long.valueOf(vTextFileNumMax.getText().trim()) <= 2)
                {
                    vTextFileNumMax.setText("3");
                }
            }
            vNumMaxPP = Long.valueOf(vTextFileNumMax.getText().trim());
        } else
        {
            if (vTextFileNumExacto.getText().length() == 0)
            {
                vTextFileNumExacto.setText("10");
            } else
            {
                if (Long.valueOf(vTextFileNumExacto.getText().trim()) <= 2)
                {
                    vTextFileNumExacto.setText("3");
                }
            }
            vNumMaxPP = Long.valueOf(vTextFileNumExacto.getText().trim());
        }
        vTextAreaConjunto.setText("================================Creando Conjunto================================");
        vTextAreaSubconjuntos0PP.setText("");
        vTextAreaTodoSubconjuntoPP.setText("");

        //////////
        vLabelTotalPP.setText("Total de subconjuntos: | Subconjuntos que suman 0: ");
        vLabelTiempoEjecPP.setText("Tiempo de ejecución: ");
        //////////
        vConjuntoPP = new CGenerar().mGenerarNoRepe(vNumMaxPP);
        mComenzarPP();

        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_vBotonGeneradorActionPerformed

    private void vBotonDetenerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vBotonDetenerActionPerformed
    {//GEN-HEADEREND:event_vBotonDetenerActionPerformed

        vBotonDetener.setEnabled(false);
        vBotonGenerador.setEnabled(true);
        vPausar = true;

    }//GEN-LAST:event_vBotonDetenerActionPerformed

    private void vTextFileNumMaxKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_vTextFileNumMaxKeyTyped
    {//GEN-HEADEREND:event_vTextFileNumMaxKeyTyped
        if (vTextFileNumMax.getText().trim().length() >= 7)
        {
            evt.consume();
        }
    }//GEN-LAST:event_vTextFileNumMaxKeyTyped

    private void vTextFileNumExactoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_vTextFileNumExactoKeyTyped
    {//GEN-HEADEREND:event_vTextFileNumExactoKeyTyped
        if (vTextFileNumMax.getText().trim().length() >= 7)
        {
            evt.consume();
        }
    }//GEN-LAST:event_vTextFileNumExactoKeyTyped

    private void vTextFileNumExactoFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_vTextFileNumExactoFocusGained
    {//GEN-HEADEREND:event_vTextFileNumExactoFocusGained
        vTextFileNumMax.setText(null);
        vNumRandomP = false;
    }//GEN-LAST:event_vTextFileNumExactoFocusGained

    private void vBotonRegresarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBotonRegresarMouseEntered
    {//GEN-HEADEREND:event_vBotonRegresarMouseEntered
        vBotonRegresar.setIcon(new ImageIcon(getClass().getResource("/pImagenes/iRegresar40.png")));
    }//GEN-LAST:event_vBotonRegresarMouseEntered

    private void vBotonRegresarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBotonRegresarMouseExited
    {//GEN-HEADEREND:event_vBotonRegresarMouseExited
        vBotonRegresar.setIcon(new ImageIcon(getClass().getResource("/pImagenes/iRegresar32.png")));
    }//GEN-LAST:event_vBotonRegresarMouseExited

    private void vBotonRegresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vBotonRegresarActionPerformed
    {//GEN-HEADEREND:event_vBotonRegresarActionPerformed
        vBotonDetener.setEnabled(false);
        vBotonGenerador.setEnabled(true);
        vPausar = true;
        dispose();
        new FSeleccion().setVisible(true);
    }//GEN-LAST:event_vBotonRegresarActionPerformed

    private void vTextFileNumMaxFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_vTextFileNumMaxFocusGained
    {//GEN-HEADEREND:event_vTextFileNumMaxFocusGained
        vTextFileNumExacto.setText(null);
        vNumRandomP = true;
    }//GEN-LAST:event_vTextFileNumMaxFocusGained

    public static String vNumCombinaciones = "";

    public static int vConteoSubConjTotal = 0;
    public static int vConteoSubconjSuma0 = 0;
    public static long[] vConjuntoPP = null;

    /**
     * Metodo para poder iniciar con la divición del conjunto, tambien escribe
     * en algunos label que se muestran en pantalla.
     *
     * @param vConjunto Conjunto generado automaticamente.
     */
    protected void mComenzarPP()
    {
        vConteoSubConjTotal = 0;
        vConteoSubconjSuma0 = 0;

        vLabelNumConjunto.setText("Longitud del conjunto: " + vConjuntoPP.length);
        System.out.println("LONGITUS: " + vConjuntoPP.length);

        String vTexto = "{";
        for (int i = 0; i < vConjuntoPP.length; i++)
        {
            if (i == vConjuntoPP.length - 1)
            {
                vTexto += " " + vConjuntoPP[i];
            } else
            {
                vTexto += vConjuntoPP[i] + ", ";
            }
            mTiempoFinalPP();
        }
        vTexto += "}";
        vTextAreaConjunto.setText(vTexto);
        BigInteger vNumSubconjuto = mCalcularSubconjuntos(vConjuntoPP.length);
        vLabelNumConjuntoInfo.setText("Longitud del conjunto: " + vConjuntoPP.length
                + ", Número de combinaciones por hacer: ");

        vLabelNumConjunto.setText(vNumSubconjuto + "");
        vNumCombinaciones = vLabelNumConjunto.getText();

        vInicioTiempo = System.nanoTime();

        Thread vHiloSubconjuntos = new SCSubconjuntosTotal();
        vHiloSubconjuntos.start();
        Thread vHiloSum0 = new SCSubconjuntosSum0();
        vHiloSum0.start();

        /*System.out.println("Paralelo:");
        for (int i = vConjunto.length; i >= 2; i--)
        {
            System.err.println("Valor i: " + i);
            Thread vHilo = new CProcesosParalelo(vConjunto, i);
            vHilo.start();
            vNumLlegarHilo++;
        }*/
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FParalelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FParalelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FParalelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FParalelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FParalelo().setVisible(true);
            }
        });
    }

    public static int vNumLlegarHilo = 0;
    public static int vNumTerminaHilo = 0;
    public static long vNumMaxPP = 0;
    public static boolean vNumRandomP = true;
    public static boolean vPausar = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JButton vBotonDetener;
    public static javax.swing.JButton vBotonGenerador;
    private javax.swing.JButton vBotonRegresar;
    public static javax.swing.JLabel vLabelNumConjunto;
    public static javax.swing.JLabel vLabelNumConjuntoInfo;
    public static javax.swing.JLabel vLabelTiempoEjecPP;
    public static javax.swing.JLabel vLabelTotalPP;
    private javax.swing.JScrollPane vScrollConjunto;
    public static javax.swing.JTextArea vTextAreaConjunto;
    public static javax.swing.JTextArea vTextAreaSubconjuntos0PP;
    public static javax.swing.JTextArea vTextAreaTodoSubconjuntoPP;
    private javax.swing.JTextField vTextFileNumExacto;
    private javax.swing.JTextField vTextFileNumMax;
    // End of variables declaration//GEN-END:variables
}

class SCSubconjuntosSum0 extends Thread
{

    String vTextSubconjunto0 = "";

    public SCSubconjuntosSum0()
    {
    }

    protected void mProcesarInforSubconjuntoSum0PP(long[] vConjunto, long[] vSubconjunto, int vLongitud, int vPosInicial)
    {
        if (vLongitud == 0)
        {
            int vSumar = 0;

            for (int i = 0; i < vSubconjunto.length; i++)
            {
                vSumar += vSubconjunto[i];
               // mTiempoFinalPP();
            }

            if (vSumar == 0)
            {
                vConteoSubconjSuma0++;
                vTextSubconjunto0 = ": {";
                for (int i = 0; i < vSubconjunto.length; i++)
                {
                    if (i == vSubconjunto.length - 1)
                    {
                        vTextSubconjunto0 += " " + vSubconjunto[i];
                    } else
                    {
                        vTextSubconjunto0 += vSubconjunto[i] + ", ";
                    }
                    //mTiempoFinalPP();
                }
                vTextSubconjunto0 += "}\n";
                vTextAreaSubconjuntos0PP.append(vConteoSubconjSuma0 + vTextSubconjunto0);
            }
            return;
        }
        for (int i = vPosInicial; i <= vConjunto.length - vLongitud; i++)
        {
            //mTiempoFinalPP();
            if (vPausar)
            {
                break;
            }
            vSubconjunto[vSubconjunto.length - vLongitud] = vConjunto[i];
            mProcesarInforSubconjuntoSum0PP(vConjunto, vSubconjunto, vLongitud - 1, i + 1);
        }
    }

    @Override
    public void run()
    {
        for (int i = vConjuntoPP.length; i >= 2; i--)
        {
            mProcesarInforSubconjuntoSum0PP(vConjuntoPP, new long[i], i, i);
        }
        System.out.println("<<Termine el conteo>>");
    }
}

class SCSubconjuntosTotal extends Thread
{

    public SCSubconjuntosTotal()
    {
    }

    @Override
    public void run()
    {
        vNumLlegarHilo=0;
        vNumTerminaHilo=0;
        System.out.println("<<Longitud delconjunto: "+vConjuntoPP.length+">>");
        for (int i = vConjuntoPP.length; i >= 2; i--)
        {
            Thread vHilo = new CProcesosParalelo(i);
            vHilo.start();
            vNumLlegarHilo++;
        }
        System.out.println("<<Total de hilos: "+vNumLlegarHilo+">>");
    }
}
