/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFrame;

import java.awt.Color;
import javax.swing.border.BevelBorder;

/**
 *
 * @author leand
 */
public class FSeleccion extends javax.swing.JFrame
{

    /**
     * Creates new form FSeleccion
     */
    public FSeleccion()
    {
        initComponents();
        vBotonComenzar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        vToggleParalelo = new javax.swing.JToggleButton();
        vToggleEstrucutal = new javax.swing.JToggleButton();
        vBotonComenzar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 210, 157));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vToggleParalelo.setBackground(new java.awt.Color(179, 148, 99));
        vToggleParalelo.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        vToggleParalelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pImagenes/iParalelo64.png"))); // NOI18N
        vToggleParalelo.setText("Paralelo");
        vToggleParalelo.setToolTipText("");
        vToggleParalelo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        vToggleParalelo.setContentAreaFilled(false);
        vToggleParalelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vToggleParalelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vToggleParalelo.setOpaque(true);
        vToggleParalelo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        vToggleParalelo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vToggleParaleloActionPerformed(evt);
            }
        });
        jPanel1.add(vToggleParalelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 133, 133));

        vToggleEstrucutal.setBackground(new java.awt.Color(179, 148, 99));
        vToggleEstrucutal.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        vToggleEstrucutal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pImagenes/iEstructural64.png"))); // NOI18N
        vToggleEstrucutal.setText("Estructural");
        vToggleEstrucutal.setToolTipText("");
        vToggleEstrucutal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        vToggleEstrucutal.setContentAreaFilled(false);
        vToggleEstrucutal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vToggleEstrucutal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vToggleEstrucutal.setOpaque(true);
        vToggleEstrucutal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        vToggleEstrucutal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vToggleEstrucutalActionPerformed(evt);
            }
        });
        jPanel1.add(vToggleEstrucutal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 133, 133));

        vBotonComenzar.setBackground(new java.awt.Color(82, 93, 37));
        vBotonComenzar.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        vBotonComenzar.setText("Comenzar");
        vBotonComenzar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vBotonComenzar.setBorderPainted(false);
        vBotonComenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBotonComenzar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vBotonComenzarActionPerformed(evt);
            }
        });
        jPanel1.add(vBotonComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 90, 30));

        jSeparator1.setBackground(new java.awt.Color(82, 93, 37));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 410, 20));

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elija el tipo de programa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vToggleParaleloActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vToggleParaleloActionPerformed
    {//GEN-HEADEREND:event_vToggleParaleloActionPerformed
       vBotonComenzar.setVisible(true);
        if (vToggleParalelo.isSelected()) //selecionado
        {
            vToggleEstrucutal.setSelected(false);
            vToggleEstrucutalActionPerformed(null);

            vToggleParalelo.setBorder(new BevelBorder(BevelBorder.LOWERED));
            vToggleParalelo.setBackground(new Color(221,167,123));

        } else //no seleccionado
        {
            vToggleParalelo.setBorder(new BevelBorder(BevelBorder.RAISED));
            vToggleParalelo.setBackground(new Color(179,148,99));
        }
    }//GEN-LAST:event_vToggleParaleloActionPerformed

    private void vToggleEstrucutalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vToggleEstrucutalActionPerformed
    {//GEN-HEADEREND:event_vToggleEstrucutalActionPerformed
       vBotonComenzar.setVisible(true);
        if (vToggleEstrucutal.isSelected()) //selecionado
        {
            vToggleParalelo.setSelected(false);
            vToggleParaleloActionPerformed(null);

            vToggleEstrucutal.setBorder(new BevelBorder(BevelBorder.LOWERED));
            vToggleEstrucutal.setBackground(new Color(221,167,123));

        } else //no seleccionado
        {
            vToggleEstrucutal.setBorder(new BevelBorder(BevelBorder.RAISED));
            vToggleEstrucutal.setBackground(new Color(179,148,99));
        }
    }//GEN-LAST:event_vToggleEstrucutalActionPerformed

    private void vBotonComenzarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vBotonComenzarActionPerformed
    {//GEN-HEADEREND:event_vBotonComenzarActionPerformed
        if (vToggleParalelo.isSelected())
        {
            System.out.println("Puchaste el paralelo");
            dispose();
            new FParalelo().setVisible(true);
        } else
        {
            System.out.println("Puchaste el Estructual");
            dispose();
            new FEstructurado().setVisible(true);
        }
    }//GEN-LAST:event_vBotonComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FSeleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton vBotonComenzar;
    private javax.swing.JToggleButton vToggleEstrucutal;
    private javax.swing.JToggleButton vToggleParalelo;
    // End of variables declaration//GEN-END:variables
}
